from decimal import Decimal

MIN_WITHDRAW_AMOUNT = Decimal("10")
MIN_TRADE_AMOUNT = Decimal("50")
MIN_RECHARGE_AMOUNT = Decimal("30")
RECHARGE_AMOUNT_TOLERANCE = Decimal("0.01")
RECHARGE_ORDER_TTL_SECONDS = 1800
RECHARGE_POLL_INTERVAL_SECONDS = 15
DEFAULT_CURRENCY = "USDT"
BCRYPT_ROUNDS = 12
SESSION_COOKIE_NAME = "kairox_session"
CSRF_HEADER_NAME = "X-CSRF-Token"
CSRF_COOKIE_NAME = "kairox_csrf"
SESSION_TTL_SECONDS = 86400
SESSION_REMEMBER_TTL_SECONDS = 86400 * 30
PASSWORD_RESET_TTL_SECONDS = 3600
INVALID_CREDENTIALS_MESSAGE = "Invalid username or password"
GENERIC_RESET_MESSAGE = "If the account exists, a reset link has been sent."
